services:
  keycloak: # Déclaration du service Keycloak
    container_name: keycloak # Définit un nom spécifique pour le conteneur (facilite son identification)
    image: quay.io/keycloak/keycloak:21.1.1 # Spécifie l'image Docker à utiliser (Keycloak version 21.1.1 depuis Quay.io)
    environment: # Liste des variables d'environnement à injecter dans le conteneur
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin} # Utilise la variable d'environnement KEYCLOAK_ADMIN définie dans le fichier .env ou par le système, sinon utilise 'admin' par défaut
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin} # Utilise la variable d'environnement KEYCLOAK_ADMIN_PASSWORD définie dans le fichier .env ou par le système, sinon utilise 'admin' par défaut
    ports:
      - "9090:8080" # Redirige le port 8080 du conteneur (port par défaut de Keycloak) vers le port 9090 de la machine hôte
    command:
      - "start-dev" # Commande exécutée lors du démarrage du conteneur (ici, démarre Keycloak en mode développement)

