services:
  keycloak-spring-boot:
    container_name: keycloak-spring-boot
    build:
      context: ./  # Le contexte de construction est le répertoire actuel
      dockerfile: Dockerfile  # Fichier Docker à utiliser
    ports:
      - "8081:8081"  # Mappe le port 8081
    networks:
      - keycloak-network  # Ajoute le service au réseau 'keycloak-network'

networks:
  keycloak-network:
    external:
      name: keycloak-network  # Utilise un réseau Docker existant appelé 'keycloak-network'
